TYPES_MAP = {
  int: ['int', 'integer', 'smallint', 'bigint', /^int\(\d+\)$/],
  varchar: ['varchar', 'character varying', /character varying\d*/, 'varchar', 'char', 'nvarchar', 'nvarchar(max)', /^varchar\(\d+\)$/],
  text: ['text', 'longtext', 'mediumtext'],
  date: ['date'],
  timestamp: ['timestamp', 'datetime'],
  boolean: ['boolean', 'bool'],
  float: ['float', 'real', 'double precision'],
  decimal: ['decimal', 'numeric',/numeric\d*/, 'money'],
  uuid: ['uuid', 'uniqueidentifier'],
  jsonb: ['jsonb', 'json'],
  array: [/\[\]$/],
  xml: ['xml'],
  bytea: ['bytea'],
}